services:
  app:
    build:
      context: .
      target: production
    command: ["python", "main.py"]
    env_file: ".env"
  dev:
    build:
      context: .
      target: test
    command: ["bash"]
    tty: true
    env_file: ".env"
    volumes:
      # Maps the current directory to /home/llcsim in the container
      # NOTE: If the app has also been run locally, directories like
      # __pycache__ will also map to the container with this volume.
      # It may be necessary to remove those directories if conflicts
      # or odd behavior arise.
      - ./src:/home/llcsim/app
      - ./tests:/home/llcsim/tests

